name: Reusable Windows MSI

on:
  workflow_call:
    inputs:
      arch:
        description: CPU architecture
        required: true
        type: string

permissions:
  contents: read

env:
  FORCE_COLOR: 1

jobs:
  build:
    name: installer for ${{ inputs.arch }}
    runs-on: ${{ inputs.arch == 'arm64' && 'windows-11-arm' || 'windows-2022' }}
    timeout-minutes: 60
    env:
      ARCH: ${{ inputs.arch }}
      IncludeFreethreaded: true
      IncludeLLVM: true
      LIBCLANG_PATH: "${{ github.workspace }}\\externals\\llvm-21.1.4.0\\bin"
    steps:
    - uses: actions/checkout@v4
      with:
        persist-credentials: false
    - uses: dtolnay/rust-toolchain@1.91.1
      with:
        targets: i686-pc-windows-msvc,x86_64-pc-windows-msvc,aarch64-pc-windows-msvc
    - name: Build CPython installer
      run: ./Tools/msi/build.bat --doc -"${ARCH}"
      shell: bash
