name: Reusable Windows

on:
  workflow_call:
    inputs:
      arch:
        description: CPU architecture
        required: true
        type: string
      llvm-from-choco:
        description: Whether to install LLVM from Chocolatey and expose LIBCLANG_PATH
        required: false
        type: boolean
        default: false
      free-threading:
        description: Whether to compile CPython in free-threading mode
        required: false
        type: boolean
        default: false

env:
  FORCE_COLOR: 1
  IncludeUwp: >-
    true

jobs:
  build:
    name: Build and test (${{ inputs.arch }})
    runs-on: ${{ inputs.arch == 'arm64' && 'windows-11-arm' || 'windows-2022' }}
    timeout-minutes: 60
    env:
      ARCH: ${{ inputs.arch }}
    steps:
    - uses: actions/checkout@v4
      with:
        persist-credentials: false
    - uses: dtolnay/rust-toolchain@1.91.1
      with:
        targets: i686-pc-windows-msvc,x86_64-pc-windows-msvc,aarch64-pc-windows-msvc
    - name: Install LLVM from Chocolatey
      if: fromJSON(inputs.llvm-from-choco)
      shell: cmd
      run: |
        choco install llvm --allow-downgrade --no-progress --version 21.1.0
        if not exist "C:\Program Files\LLVM\bin\libclang.dll" exit /b 1
        echo IncludeLLVM=false>> "%GITHUB_ENV%"
        echo LIBCLANG_PATH=C:\Program Files\LLVM\bin>> "%GITHUB_ENV%"
        echo LLVMInstallDir=C:\Program Files\LLVM>> "%GITHUB_ENV%"
    - name: Use bundled LLVM
      if: ${{ !fromJSON(inputs.llvm-from-choco) }}
      shell: cmd
      run: |
        echo IncludeLLVM=true>> "%GITHUB_ENV%"
        echo LIBCLANG_PATH=%GITHUB_WORKSPACE%\externals\llvm-21.1.4.0\bin>> "%GITHUB_ENV%"
    - name: Register MSVC problem matcher
      if: inputs.arch != 'Win32'
      run: echo "::add-matcher::.github/problem-matchers/msvc.json"
    - name: Build CPython
      run: >-
        .\\PCbuild\\build.bat
        -e -d -v
        -p "${ARCH}"
        ${{ fromJSON(inputs.free-threading) && '--disable-gil' || '' }}
      shell: bash
    - name: Display build info
      run: .\\python.bat -m test.pythoninfo
    - name: Tests
      run: >-
        .\\PCbuild\\rt.bat
        -p "${ARCH}"
        -d -q --fast-ci
        ${{ fromJSON(inputs.free-threading) && '--disable-gil' || '' }}
      shell: bash
